// All user-facing copy for the SwiftStatement workspace, ported from the canvas source.
// The account holder was originally a real Australian buying group; it is genericised here
// to the same fictional name used on the intro screen.

export const workspace = {
  title: "Tradeline Group statement",
  subtitle: "Your interactive trade account statement.",
  settingsTitle: "Settings",
  refreshTitle: "Fetch the latest statement lines",

  credit: {
    title: "Credit health",
    subtitle: "Based on your current Xero-recorded liability",
    usedLabel: "Used credit",
    liabilityLabel: "Trade account liability",
    liabilityCaption: "Total outstanding debt",
    availableLabel: "Available credit",
    availableCaption: "Remaining spend capacity",
  },
  spend: {
    title: "Monthly spend",
    subtitle: "New charges posted this month",
    statLabel: "Spent this month",
    pillSpend: "Monthly spend",
    pillCredit: "Credit health",
  },

  filters: {
    searchPlaceholder: "Search transactions, suppliers, or references…",
    recon: [
      { id: "all", label: "All" },
      { id: "reconciled", label: "Reconciled" },
      { id: "unreconciled", label: "Unreconciled" },
    ],
    type: [
      { id: "all", label: "All" },
      { id: "debits", label: "Debits" },
      { id: "credits", label: "Credits" },
    ],
    columnsLabel: "Columns",
    columnsHeading: "Show / hide columns",
  },

  xeroImport: {
    title: "Xero import",
    subtitle: "Manage transaction imports",
  },

  table: {
    supplier: "Supplier & type",
    reference: "Reference",
    poReference: "PO reference",
    transactionDate: "Transaction date",
    statementPeriod: "Statement period",
    dueDate: "Due date",
    amount: "Amount",
    reconciliation: "Reconciliation",
    action: "Action",
    unreconciled: "Unreconciled",
    viewInXero: "View in Xero",
    reconInfoTitle: "About reconciliation statuses",
  },

  reconInfo: {
    title: "Reconciliation statuses",
    subtitle: "How each statement line moves through the reconciliation workflow",
  },

  match: {
    title: "Reconcile statement line",
    subWithCandidates:
      "Match this line to an existing transaction in Xero, or post it as a new one if no match exists.",
    statementLine: "Statement line",
    amountOnStatement: "Amount on statement",
    invoiceRef: "Invoice ref",
    invoiceDate: "Invoice date",
    dueDate: "Due date",
    statementPeriod: "Statement period",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    tabMatchTitle: "Match to an existing invoice",
    tabMatchSubAvailable: "Already in Xero",
    tabMatchSubNone: "None available",
    tabPostTitle: "Approve and post invoice",
    tabPostSub: "Not in Xero yet",
    candidateSearchPlaceholder: "Search by ref number or amount…",
    candidateEmpty: "No invoices match your search",
    colRef: "Ref no.",
    colDate: "Invoice date",
    colTotal: "Total",
    colAction: "Action",
    preview: "Preview",
    potentialMatch: "Potential match",
    writeOffTitle: "Write it off",
    leaveTitle: "Leave it unaccounted",
    leaveBody: "Match anyway and handle the difference separately.",
    productLabel: "Product category",
    productPlaceholder: "Select a category…",
    productHelp:
      "Sets the expense account this invoice posts to in Xero — pick the category that matches the goods.",
    postsToAccount: "Posts to account",
    invoiceAmount: "Invoice amount",
    invoiceAmountHelp: "Total includes tax. Edit either amount — the subtotal updates to match.",
    cancel: "Cancel",
    reconcileCta: "Reconcile statement",
    reconcileCtaDisabled: "Select an invoice to reconcile",
    postCta: "Approve & post invoice",
    postCtaNoProduct: "Select a category to post",
    postCtaBadTax: "Fix the tax amount to post",
    previewOverline: "Xero invoice",
    previewStatus: "Awaiting payment",
    previewDescription: "Trade supply — goods",
    previewStatusLabel: "Status",
    previewDescriptionLabel: "Description",
    previewTaxLabel: "Tax (10%)",
  },

  verify: {
    title: "Verify transaction details",
    subtitle:
      "Confirm the product category and tax amount for each transaction before posting to Xero.",
    countLabel: "Transactions to post",
    totalTaxLabel: "Total tax",
    totalAmountLabel: "Total amount",
    colSupplier: "Supplier & ref",
    colProduct: "Product category",
    colTax: "Tax amount",
    colTotal: "Trans total",
    supplierLabel: "Supplier",
    transactionLabel: "Transaction",
    productLabel: "Product category",
    taxLabel: "Tax amount",
    transTotalLabel: "Trans total",
    cancel: "Cancel",
  },

  supplier: {
    step1Title: "Link supplier",
    step2Title: "Set posting behaviour",
    step1Label: "Link supplier",
    step2Label: "Posting behaviour",
    onYourStatement: "On your statement",
    inYourXero: "In your Xero",
    choosePlaceholder: "Choose a supplier below",
    searchPlaceholder: "Search all Xero suppliers…",
    emptyList: "No suppliers found",
    likelyMatch: "Likely match",
    createCta: "Can't find them? Create a new supplier in Xero",
    backToSearch: "Back to search",
    detailsHeading: "Supplier details",
    businessNameLabel: "Business name",
    businessNamePlaceholder: "Business Pty Ltd",
    abnLabel: "ABN",
    abnPlaceholder: "00 000 000 000",
    abnEmpty: "Enter the supplier's ABN",
    abnShort: "Enter the 11-digit ABN",
    abnInvalid: "Please enter a valid ABN",
    abnValid: "ABN verified",
    newSupplier: "New supplier",
    productLabel: "Default product",
    productPlaceholder: "Select a product…",
    productHelp: "What you typically buy from this supplier",
    expenseAccount: "Expense account",
    setByProduct: "Set by product",
    back: "Back",
    cancel: "Cancel",
    next: "Next",
    save: "Save changes",
  },

  tour: {
    cta: "Show me around",
    skip: "Skip",
    next: "Next",
    done: "Got it",
    steps: [
      {
        target: "#tour-credit",
        title: "Your credit health at a glance",
        body: "This panel shows what you owe on your trade account, how much credit you have left, and when the statement was last refreshed.",
      },
      {
        target: "#tour-table",
        title: "Your statement, line by line",
        body: "Every transaction charged to the account this period sits below — invoices, credit notes and payments, all in one list.",
      },
      {
        target: '[data-tour-action="link"]',
        title: "Only these need you",
        body: "Most lines reconcile themselves. The ones that can't show an action button with the reason. Click Link supplier to reconcile this one.",
      },
    ],
  },
};

export const TOUR_STORAGE_KEY = "ss-tour-seen";
