// Settings + Mappings copy, ported from the canvas source. The original was branded to a
// real fintech; all vendor branding is removed here (see AGENTS.md).

export const settings = {
  backToStatement: "Trade account",
  title: "Organisation settings",
  subtitle: "Manage your business details, users, and integrations",
  tabs: [
    { id: "business", label: "Business details", icon: "building-2" },
    { id: "users", label: "Users & roles", icon: "users" },
    { id: "integrations", label: "Integrations", icon: "plug" },
    { id: "swift", label: "SwiftStatement settings", icon: "file-text" },
  ],
  business: {
    cardTitle: "Business details",
    cardDesc: "Update your organisation's business information",
    logoLabel: "Business logo",
    change: "Change",
    remove: "Remove",
    tradingName: "Trading name",
    tradingNameValue: "Tenant Twenty LIVE",
    abnLabel: "ABN",
    abnValue: "97 164 904 483",
    abnHelp: "Australian Business Number is mandatory",
    phone: "Phone",
    phoneValue: "0412 553 310",
    email: "Email",
    emailPlaceholder: "accounts@business.com.au",
    website: "Website",
    websitePlaceholder: "https://",
    requiredNote: "* Required field",
    save: "Save changes",
    savedToast: "Business details saved",
  },
  users: {
    cardTitle: "Users & roles",
    cardDesc: "Manage who can access this business and what they can do",
    add: "Add user",
    youBadge: "You",
    list: [
      { initials: "AM", name: "Ado Mullee", email: "ado@tenanttwenty.com.au", role: "Administrator", you: true },
      { initials: "JR", name: "Jess Ryan", email: "jess@tenanttwenty.com.au", role: "Accounts payable" },
      { initials: "TC", name: "Tom Chen", email: "tom@tenanttwenty.com.au", role: "Viewer" },
    ],
  },
  integrations: {
    cardTitle: "Integrations",
    cardDesc: "Connect SwiftStatement to your accounting and banking systems",
    xeroName: "Xero",
    xeroMeta: "Accounting · Tenant Twenty LIVE",
    connected: "Connected",
    manage: "Manage",
    bankName: "Bank feed",
    bankMeta: "Not connected",
    connect: "Connect",
    legacyNote: "Temporarily, some integrations are managed in the previous SwiftStatement settings.",
    legacyCta: "Open legacy integration settings",
    legacyTitle: "Legacy integration settings",
    legacyDesc: "Opens the previous settings experience",
    legacyChip: "Legacy",
  },
  swift: {
    cardTitle: "SwiftStatement settings",
    cardDesc: "Control how trade account statements reconcile and post to Xero",
    featuresLabel: "Features",
    toggles: [
      {
        id: "xeroEnabled",
        title: "Xero connection enabled",
        desc: "Show the Xero import panel, reconciliation column, and reconciliation filters",
      },
      {
        id: "enablePayments",
        title: "Payments enabled",
        desc: "Show payment functionality and the sticky payment footer",
      },
      {
        id: "repayOnPayment",
        title: "Repay on payment",
        desc: "Automatically clear the trade account liability when a bill is paid",
      },
    ],
    creditLineLabel: "Credit line",
    creditLimitLabel: "Trade account credit limit",
    creditLimitHelp: "Set the maximum credit available on your trade account",
    liabilityLabel: "Xero liability account",
    liabilityHelp: "Choose which liability account to create invoices against",
    mappingsLabel: "Mappings",
    mappingsTitle: "Supplier & product mappings",
    mappingsDesc:
      "Map suppliers to default products, and products to Xero inventory items used when posting invoices.",
    mappingsCta: "Manage mappings",
    footNote: "Changes apply to your trade account statement",
    save: "Save changes",
    savedToast: "SwiftStatement settings saved",
  },
  chartOfAccounts: [
    { id: "swift-credit-line", name: "SwiftStatement Credit Line" },
    { id: "trade-creditors", name: "Trade Creditors" },
    { id: "accounts-payable", name: "Accounts Payable" },
    { id: "gst-payable", name: "Tax Payable" },
    { id: "other-creditors", name: "Other Creditors" },
    { id: "directors-loan", name: "Director's Loan Account" },
  ],
  defaults: {
    xeroEnabled: true,
    enablePayments: true,
    repayOnPayment: false,
    creditLimit: 300000,
    liabilityAccount: "swift-credit-line",
  },
};

export const mappings = {
  backToStatement: "Trade account",
  backToSettings: "SwiftStatement settings",
  title: "Mappings",
  subtitle:
    "Map how trade account statement lines flow into Xero — supplier to product, then product to chart of accounts category.",
  views: [
    { id: "suppliers", label: "Suppliers → products", icon: "forklift" },
    { id: "products", label: "Products → accounts", icon: "arrow-left-right" },
  ],
  supplierIntro:
    "Each supplier on your trade account statement, the Xero supplier record they're linked to, and the default product SwiftStatement assigns when it posts their invoices.",
  productIntro:
    "Each SwiftStatement product and the chart of accounts category it posts against in Xero. This sets how costs for the product are categorised on your financial system.",
  supplierSearchPlaceholder: "Search suppliers…",
  productSearchPlaceholder: "Search products…",
  colSupplier: "Supplier",
  colLinked: "Linked supplier",
  colDefaultProduct: "Default product",
  colProduct: "Product",
  colAccount: "Chart of accounts category",
  notLinked: "Not linked",
  emptySuppliers: "No suppliers match your search",
  emptyProducts: "No products match your search",
  footNote: "Changes apply when SwiftStatement posts invoices to Xero",
  save: "Save changes",
  savedToast: "Mappings saved",
  supplierRows: [
    { id: "cwa", name: "Carpet Wholesalers Australia", xero: "Carpet Wholesalers Pty Ltd", product: "Carpet — broadloom" },
    { id: "qtf", name: "Quality Timber Flooring", xero: "Quality Timber Flooring Co", product: "Timber flooring" },
    { id: "mtw", name: "Metro Tile Warehouse", xero: "Metro Tile Warehouse", product: "" },
    { id: "upl", name: "Underlay Plus", xero: "Underlay Plus Supplies", product: "Underlay & padding" },
    { id: "vfd", name: "Vinyl & Flooring Direct", xero: "", product: "Vinyl & laminate" },
  ],
  coaAccounts: [
    { code: "5000", label: "Cost of goods sold" },
    { code: "5100", label: "Materials & supplies" },
    { code: "6000", label: "Purchases" },
    { code: "6200", label: "Freight & courier" },
    { code: "6300", label: "Subcontractor costs" },
    { code: "6400", label: "Operating expenses" },
  ],
  productAccountSeed: {
    "Carpet — broadloom": "5000",
    "Underlay & padding": "5000",
    "Timber flooring": "5000",
    "Vinyl & laminate": "5000",
    "Installation accessories": "5100",
    "Freight & delivery": "6200",
    "Adhesives & sealants": "",
    "Trims & edging": "",
  } as Record<string, string>,
  mapProducts: [
    "Carpet — broadloom",
    "Underlay & padding",
    "Timber flooring",
    "Vinyl & laminate",
    "Installation accessories",
    "Freight & delivery",
    "Adhesives & sealants",
    "Trims & edging",
  ],
};
